version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - mydb
    env_file:
      - .env
    environment:
      - PORT=5555
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=pos
    volumes:
      - ./src:/usr/src/app/src

  mydb:
    image: postgres:13
    container_name: mydb
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - mydb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: mypgadmin
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - mydb

volumes:
  mydb:
    name: nest-prisma-docker-db
