version: '3.8'
services:
  posdb:
    image: postgres:15
    container_name: posdb
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - posdb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - posdb

volumes:
  posdb:
    name: pos-volumes
